version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - DATABASE_URL=mongodb+srv://bebon:123321@interview.xzgdy.mongodb.net/Test?retryWrites=true&w=majority&appName=Interview?authSource=admin
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
    volumes:
      - .:/src
    networks:
      - node-network

  mongodb:
    image: mongo:4Interview
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge
