version: latest

services:
  dev:
    build: .
    image: mongo:latest
    restart: always
    expose:
      - 8080
    ports:
      - '8080:8080'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}

volumes:
  mongo_data:
