### Auth HTTP Requests

### SignUp
POST http://localhost:3333/auth/signup
Content-Type: application/json

{
    "email": "asdf@asdf.com",
    "password": "yourPassword",
    "name": "John Doe"
}

### SignIn
POST http://localhost:3333/auth/signin
Content-Type: application/json

{
    "email": "asdf@asdf.com",
    "password": "yourPassword"
}


### User HTTP Requests

### Invite User
POST http://localhost:3333/organization/672017397b9c9b141e32951c/invite
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzIwMTcyNzdiOWM5YjE0MWUzMjk1MWIiLCJlbWFpbCI6ImFzZGZAYXNkZi5jb20iLCJpYXQiOjE3MzAxNTkzMzcsImV4cCI6MTczMDE2MTEzN30.ZVblvkHhWRA0WOhy_jcAFA4rISpA69I-8uuFmgj3o98

{
    "email": "asdf@asdf.com"
}


### Organization HTTP Requests

### Create Organization
POST http://localhost:3333/organization
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzIwMTcyNzdiOWM5YjE0MWUzMjk1MWIiLCJlbWFpbCI6ImFzZGZAYXNkZi5jb20iLCJpYXQiOjE3MzAyMjY4MjgsImV4cCI6MTczMDIyODYyOH0.apDKCtDtuuw6peCcUxD5vKMRwnrTHCXVIUcQlCHgIjg

{
    "name": "lol Organization",
    "description": "This is test organization"
}

### Get All Organizations
GET http://localhost:3333/organization
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzIwMTcyNzdiOWM5YjE0MWUzMjk1MWIiLCJlbWFpbCI6ImFzZGZAYXNkZi5jb20iLCJpYXQiOjE3MzAxNTkzMzcsImV4cCI6MTczMDE2MTEzN30.ZVblvkHhWRA0WOhy_jcAFA4rISpA69I-8uuFmgj3o98
### Get Organization By Id
GET http://localhost:3333/organization/67200f3969b456532a746df2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzIwMTcyNzdiOWM5YjE0MWUzMjk1MWIiLCJlbWFpbCI6ImFzZGZAYXNkZi5jb20iLCJpYXQiOjE3MzAxNTYzMzQsImV4cCI6MTczMDE1ODEzNH0.iw7pjQgNoElYVGjRv8mIVraFN4N-6vYt4R4-UZhBjGc

### Update Organization
PUT http://localhost:3333/organization/67200f3969b456532a746df2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzIwMTcyNzdiOWM5YjE0MWUzMjk1MWIiLCJlbWFpbCI6ImFzZGZAYXNkZi5jb20iLCJpYXQiOjE3MzAxNTYzMzQsImV4cCI6MTczMDE1ODEzNH0.iw7pjQgNoElYVGjRv8mIVraFN4N-6vYt4R4-UZhBjGc

{
    "name": "My Organization 2",
    "description": "This is my organization 2"
}

### Delete Organization
DELETE http://localhost:3333/organization/67200f3969b456532a746df2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzIwMTcyNzdiOWM5YjE0MWUzMjk1MWIiLCJlbWFpbCI6ImFzZGZAYXNkZi5jb20iLCJpYXQiOjE3MzAxNTYzMzQsImV4cCI6MTczMDE1ODEzNH0.iw7pjQgNoElYVGjRv8mIVraFN4N-6vYt4R4-UZhBjGc
